name: Clear Downloads Folder

on:
  workflow_dispatch:
    inputs:
      warning:
        description: '⚠️ WARNING: This will DELETE ALL files inside downloads/ folder. Click "Run workflow" only if you are sure.'
        required: false
        default: 'Read this warning before proceeding'
        type: string

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Delete all files
        run: rm -rf downloads/*
